"File: Video":
- '**/*.mp4'
- '**/*.mov'

"File: Audio":
- '**/*.mp3'
- '**/*.ogg'
- '**/Resources/Audio/**'

"File: Text":
- '**/*.txt'

"File: Textures":
- '**/Resources/Textures/**'
- '**/meta.json'

"File: github":
- '.github/**'

"File: Role":
- '**/Resources/Prototypes/Roles/**'

"File: Localization":
- '**/*.ftl'

"File: Entity":
- '**/Resources/Prototypes/Entities/**'

"NOT TO MERGE":
- '**/SECURITY.md'
- '**/LICENSE.txt'

"File: passport":
- '**/passports.*'