# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '45 21 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Этот Issue неактивен более 60 дней. Он будет закрыт через 7 дней автоматически'
        stale-pr-message: 'Этот PR неактивен более 60 дней. Он будет закрыт через 7 дней автоматически'
        stale-issue-label: 'AFK'
        stale-pr-label: 'AFK'
